name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x64
            os: ubuntu-latest
          - build: macos-x64
            os: macos-latest
          - build: windows-x64
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.84
      - name: build
        run: cargo run --release --example simple
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            target/release/examples/tesseract/libleptonica.dylib
            target/release/examples/tesseract/libtesseract.dylib
            target/release/examples/tesseract/libleptonica.so
            target/release/examples/tesseract/libtesseract.so
            target/release/examples/tesseract/libleptonica.dll
            target/release/examples/tesseract/libtesseract.dll